# Generated by Django 4.2 on 2025-12-04 16:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('Tag_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Animal_type', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Breed', models.CharField(max_length=20)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Livestock',
            },
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('Mid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Equipment_name', models.CharField(max_length=20)),
                ('Purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Purchase_date', models.DateField()),
                ('Operation', models.TextField(blank=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Machinery',
            },
        ),
        migrations.CreateModel(
            name='Milk_production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('Month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('Day', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('Livestock_number', models.IntegerField()),
                ('Morning_production', models.DecimalField(decimal_places=2, help_text='production in litres', max_digits=10)),
                ('Midday_production', models.DecimalField(blank=True, decimal_places=2, help_text='production in litres', max_digits=10)),
                ('Evening_production', models.DecimalField(blank=True, decimal_places=2, help_text='production in litres', max_digits=10)),
                ('Total_production', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('Morning_consumption', models.DecimalField(decimal_places=2, help_text='feed consumed in kg', max_digits=10)),
                ('Evening_consumption', models.DecimalField(blank=True, decimal_places=2, help_text='feed consumed in kg', max_digits=10)),
                ('Total_consumption', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Machinery_maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(help_text='m/d/y')),
                ('Machinery_part', models.CharField(max_length=100)),
                ('Technician_details', models.CharField(blank='True', max_length=100)),
                ('Cost', models.IntegerField()),
                ('Description', models.TextField()),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.machinery')),
            ],
            options={
                'db_table': 'Machinery_activities',
            },
        ),
        migrations.CreateModel(
            name='Machinery_activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_date', models.DateField(help_text='m/d/y')),
                ('Activity_type', models.CharField(max_length=20)),
                ('Activity_cost', models.IntegerField(blank=True)),
                ('Description', models.TextField(blank=True)),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.machinery')),
            ],
        ),
        migrations.CreateModel(
            name='Livestock_production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Production_date', models.DateField(help_text='m/d/y')),
                ('Production_amount', models.CharField(max_length=20)),
                ('Feed_consumed', models.DecimalField(decimal_places=2, help_text='field consumed in kg', max_digits=10)),
                ('Comments', models.TextField(blank=True, null=True)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.livestock')),
            ],
            options={
                'db_table': 'Livestock_production',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('Eid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Phone_number', models.CharField(max_length=10)),
                ('Position', models.CharField(max_length=10)),
                ('Salary', models.IntegerField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Eggs_production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('Month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('Day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('Poultry_number', models.IntegerField()),
                ('Morning_egg_collection', models.DecimalField(decimal_places=2, help_text='total number of eggs collected', max_digits=10)),
                ('Midday_egg_collection', models.DecimalField(blank=True, decimal_places=2, help_text='total number of eggs collected', max_digits=10)),
                ('Evening_egg_collection', models.DecimalField(blank=True, decimal_places=2, help_text='total number of eggs collected', max_digits=10)),
                ('Total_egg_collection', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('Morning_feeds', models.DecimalField(decimal_places=2, help_text='feed consumed in kg', max_digits=10)),
                ('Evening_feeds', models.DecimalField(blank=True, decimal_places=2, help_text='feed consumed in kg', max_digits=10)),
                ('Total_feeds', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('Comments', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('Cid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Field_name', models.CharField(max_length=50)),
                ('Field_description', models.TextField()),
                ('Crop_name', models.CharField(max_length=50)),
                ('Variety', models.CharField(max_length=20)),
                ('Planting_date', models.DateField()),
                ('Is_harvested', models.BooleanField(default=False)),
                ('Harvesting_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crop_sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sale_date', models.DateField(help_text='m/d/y')),
                ('Quantity_sold', models.CharField(max_length=20)),
                ('Unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('Buyer_information', models.TextField()),
                ('Payment_method', models.CharField(max_length=20)),
                ('Payment_status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received')], max_length=20)),
                ('Invoice_number', models.CharField(max_length=20)),
                ('Additional_notes', models.TextField(blank=True)),
                ('crops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.crops')),
            ],
        ),
        migrations.CreateModel(
            name='Crop_operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operation_date', models.DateField(help_text='m/d/y')),
                ('Operation_name', models.CharField(max_length=20)),
                ('Additional_notes', models.TextField(blank=True)),
                ('crops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.crops')),
            ],
            options={
                'db_table': 'Crop_operations',
            },
        ),
        migrations.CreateModel(
            name='Crop_expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expense_date', models.DateField(help_text='m/d/y')),
                ('Expense_type', models.CharField(max_length=20)),
                ('Expense_description', models.TextField()),
                ('Budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Expense_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Supplier', models.CharField(max_length=20)),
                ('Payment_method', models.CharField(max_length=10)),
                ('Receipt_number', models.CharField(max_length=20)),
                ('crops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.crops')),
            ],
            options={
                'db_table': 'Crop_expenses',
            },
        ),
    ]
