# Generated by Django 4.2 on 2025-12-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinery',
            old_name='Mid',
            new_name='Number_plate',
        ),
    ]
