# Generated by Django 4.2 on 2025-12-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_mid_machinery_number_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinery',
            name='Number_plate',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='machinery_maintenance',
            table='Machinery_maintenance',
        ),
    ]
