# Generated by Django 4.2 on 2025-12-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_machinery_number_plate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinery',
            name='Number_plate',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
