# Generated by Django 4.2 on 2025-12-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_machinery_number_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinery',
            name='Purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
