# Generated by Django 4.2 on 2025-12-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_machinery_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milk_production',
            name='Month',
            field=models.CharField(max_length=100),
        ),
    ]
