# Generated by Django 4.2 on 2025-12-05 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_milk_production_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milk_production',
            name='Month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
