# Generated by Django 4.2 on 2025-12-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_milk_production_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Position',
            field=models.CharField(max_length=50),
        ),
    ]
