# Generated by Django 4.2 on 2025-12-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_alter_employees_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
