# Generated by Django 4.2 on 2025-12-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_alter_employees_phone_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='livestock_production',
            unique_together={('livestock', 'Production_date')},
        ),
        migrations.AlterModelTable(
            name='livestock_production',
            table=None,
        ),
    ]
