# Generated by Django 4.2 on 2025-12-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_alter_livestock_production_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='livestock_production',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='livestock_production',
            table='Livestock_production',
        ),
    ]
