# Generated by Django 4.2 on 2025-12-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_alter_livestock_production_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_sales',
            name='Additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
