# Generated by Django 4.2 on 2025-12-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_alter_crop_sales_additional_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_operations',
            name='Additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
