# Generated by Django 4.2 on 2025-12-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_alter_crop_operations_additional_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinery',
            name='Operation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machinery_activities',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
